# Generated by rust2rpm 26
# Disable tests by default, since they require a running ssh-agent with keys
%bcond check 0

# prevent library files from being installed
%global cargo_install_lib 0

Name:           pam_rssh
Version:        1.2.0~rc2
Release:        %autorelease
Summary:        PAM module for ssh-agent based authentication

SourceLicense:  MIT
License:        Apache-2.0 AND (BSD-2-Clause OR Apache-2.0) AND CC-PDDC AND MIT AND (MIT OR Apache-2.0) AND (Unlicense OR MIT)

URL:            https://github.com/z4yx/pam_rssh
Source:         %{name}-%{version}.tar.xz
Source:         %{name}-%{version}-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  openssl-devel
BuildRequires:  pam-devel

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n %{name}-%{version} -p1 -a1
%cargo_prep -v vendor

%build
mv dep/ssh-agent.rs/LICENSE dep/ssh-agent.rs/ssh-agent.rs.LICENSE
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
install -d -m 755 %{buildroot}%{_libdir}/security
install -m 755 target/release/libpam_rssh.so %{buildroot}%{_libdir}/security

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license dep/ssh-agent.rs/ssh-agent.rs.LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_libdir}/security/libpam_rssh.so

%changelog
%autochangelog
